load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    deps = ["//src/procedureHead:procedureHead", "//src/parsing:parser", "//src/debug:debug", "//src/symbolTable:symbolTable"],
)